### ISSUE TITLE
Non-functionality NitPicks

### ISSUE THREAD

**Issue by RaymondChen2018** [nardost/clean-sweep-robot#33]
- Migrate SensorSimulator's isFloorDone to RobotCleanSweep, since sensor shouldn't possess any memory of traversal work, Rename "visitedAll()" in RobotCleanSweep to "isFloorDone()".

- Remove all getters of **privately-used** elements in RobotCleanSweep: eg. getNavigator(). 
The getters are unnecessary and confusing when trying to read other important code. When need to, refer the instance directly instead. (contriversal)

- Tile class doesn't need isOpen methods, a tile shouldn't know about its neighboors; there can be a class called "floorplan_simulator" to judge if a tile is open to four directions based on input from the robot about its current position;

- Sensor doesn't access directly from "Tile" class, but from the "floorplan_simulator"; eg. 
Sensor_method(){
bool westOpen = floorplan_simulator.getInstance().isWestOpen(robotPosition)
}

**Comment by nardost** [comment]
Regarding accessors and mutators (getters and setters), it is only a matter of opinion and should not affect our productivity. Don't forget , though, that setters are the recommended point of data validation. I personally consider them a good practice and have been nurturing the habit for a while.

**Comment by nardost** [comment]
SensorSimulator's isFloorDone has nothing to do with Robot's floor traversal. I initially added it to give the information if there are any uncleaned tiles on the floor. Robot can query that to make sure it has cleaned all dirty tiles.

**Comment by nardost** [comment]
SensorSimulator is a Facade. It hides details and gives only required info via a DAO object (FloorDao). The internals are working  for us so far, and I don't see why we should change it at this point.
